### PR TITLE
Fix scan so it compiles on FreeBSD and OpenBSD

### PR DESCRIPTION
**Pull request by ghost**
With this diff, scan compiles on FreeBSD and OpenBSD.  It also runs on FreeBSD and works fine.
netinet/in.h is included in socket.cpp now, so sockaddr_in can be used:
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/netinet_in.h.html
A nearly empty .depend file is made, since it needs to exist for builds to proceed.
And in the makefile, g++ is swapped with c++, which should work on every operating system I know of, including ones that use GCC and ones that use Clang. (this part of the diff is optional though)

However, scan does not run on OpenBSD.  I don't know why:
```
tewi$ ./scan                                                                                                                                                                                                                                                  

init book
Illegal instruction (core dumped) 
```
I also get this compile warning while compiling on OpenBSD:
```
c++ -pthread -std=c++14 -fno-rtti -O2 -mpopcnt -flto -DNDEBUG  -c search.cpp
search.cpp:559:103: warning: format specifies type 'long' but the argument has type 'int64' (aka 'long long') [-Wformat]
         std::printf("%2d/%4.1f%+7.2f%11ld%7.2f%5.1f  %s\n", depth, ply_avg(), double(score) / 100.0, node, time, speed / 1E6, pv.to_string(m_pos, 7).c_str());
                                     ~~~~~                                                            ^~~~
                                     %11lld
1 warning generated.
```
The warning could probably be fixed by including and using inttypes.h but I didn't do that in this diff.

I'm also submitting this diff here on github since I didn't find the original author's email address. :B

### CODE REVIEW

**Comment by rhalbersma** [comment]
Thanks for your PR! It looks good to me. However, this repo is simply a mirror of the code that is published at https://hjetten.home.xs4all.nl/scan/scan.html

The author of Scan (Fabien Letouzey) does not maintain his own GitHub repo. You can contact him by email (see the readme.txt). For now, I have forwarded your PR to him. If he incorporates your PR in his own codebase and publishes this, I will mirror that here.

**Comment by ghost** [comment]
> Thanks for your PR! It looks good to me. However, this repo is simply a mirror of the code that is published at https://hjetten.home.xs4all.nl/scan/scan.html
> 
> The author of Scan (Fabien Letouzey) does not maintain his own GitHub repo. You can contact him by email (see the readme.txt). For now, I have forwarded your PR to him. If he incorporates your PR in his own codebase and publishes this, I will mirror that here.

Thanks so much!   I missed it in the readme.txt, my bad, heh. :B
If you've forwarded it to him, that's good.  I'll send him a short email too.

**Comment by rhalbersma** [comment]
Closing for now. If this is incorporated upstream, it will eventually be mirrored here.

**Comment by ghost** [comment]
Note (mostly to self, so I don't forget) that the -mpopcnt in src/Makefile is only valid on x86, and on other hardware architectures is an invalid flag that stops builds. (found that out on ARM64)

**Pull request closed without merging**
